<?php
  include("connection/connect.php");
  include("functions/article.func.php");
  include("functions/user.func.php");
  include("functions/post.func.php");
  include("functions/news.func.php");
  include("functions/search.func.php");
  include("functions/image.func.php");
  $GLOB_URL="http://localhost/church/";
?>
